name: Build ChameleonMini GUI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'
    
    - name: Restore NuGet packages
      run: |
        nuget restore ChameleonMiniGUI.sln -PackagesDirectory packages
    
    - name: Build solution
      run: |
        msbuild ChameleonMiniGUI.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=bin\Release\
    
    - name: Copy dependencies to output directory
      run: |
        # Copy HexBox DLL
        Copy-Item "Be.Windows.Forms.HexBox\bin\Release\Be.Windows.Forms.HexBox.dll" "ChameleonMiniGUI\bin\Release\" -Force
        
        # Copy Crapto1Sharp DLL
        Copy-Item "packages\Crapto1Sharp.1.2.2\lib\net45\Crapto1Sharp.dll" "ChameleonMiniGUI\bin\Release\" -Force
        
        # Copy DynamicExpresso DLL
        Copy-Item "packages\DynamicExpresso.Core.2.0.0\lib\net461\DynamicExpresso.Core.dll" "ChameleonMiniGUI\bin\Release\" -Force
      shell: powershell
    
    - name: Verify build outputs
      run: |
        if (!(Test-Path "Be.Windows.Forms.HexBox\bin\Release\Be.Windows.Forms.HexBox.dll")) {
          throw "HexBox DLL not found"
        }
        if (!(Test-Path "ChameleonMiniGUI\bin\Release\ChameleonMiniGUI.exe")) {
          throw "Main executable not found"
        }
        Write-Host "Build verification passed" -ForegroundColor Green
      shell: powershell
    
    - name: Run tests (if available)
      run: |
        if (Test-Path "ChameleonTest\ChameleonTest.sln") {
          Write-Host "Running tests..." -ForegroundColor Yellow
          nuget restore ChameleonTest\ChameleonTest.sln -PackagesDirectory ChameleonTest\packages
          msbuild ChameleonTest\ChameleonTest.sln /p:Configuration=Release
          
          if (Test-Path "ChameleonTest\ChameleonTest\bin\Release\ChameleonTest.dll") {
            vstest.console.exe "ChameleonTest\ChameleonTest\bin\Release\ChameleonTest.dll"
          }
        } else {
          Write-Host "No tests found, skipping test execution" -ForegroundColor Yellow
        }
      shell: powershell
      continue-on-error: true
    
    - name: Create release package
      run: |
        $releaseDir = "ChameleonMiniGUI\bin\Release"
        $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
        $archiveName = "ChameleonMiniGUI-$timestamp.zip"
        
        # Create zip archive
        Compress-Archive -Path "$releaseDir\*" -DestinationPath $archiveName -Force
        
        Write-Host "Created release package: $archiveName" -ForegroundColor Green
      shell: powershell
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ChameleonMiniGUI-Build-${{ github.run_number }}
        path: |
          ChameleonMiniGUI/bin/Release/
          !ChameleonMiniGUI/bin/Release/*.pdb
        retention-days: 30
    
    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: ChameleonMiniGUI-Release-Package
        path: ChameleonMiniGUI-*.zip
        retention-days: 90
